#!/usr/bin/env bash
PROMPT="This is speech generated by the TTS CPP library."
MODELS_DIR="models"
BASE_MODEL="parler-tts-mini-v1"

rm *.wav
echo Testing fp32
time ./cli -mp "${MODELS_DIR}/${BASE_MODEL}-fp32.gguf" -p "${PROMPT}" -sp "fp32.wav"
for qt in $(cat qt.txt)
do
    QT=$(echo "${qt}" | cut -d "," -f 1)
    echo Testing "${QT}"
    time ./cli -mp "${MODELS_DIR}/${BASE_MODEL}-${QT}.gguf" -p "${PROMPT}" -sp "${QT}.wav"
done
